import Head from "next/head"
import Layout from "@/components/Layout/Layout"
import Hero from "@/components/Hero/Hero"
import Events from "@/components/Events/Events"
import Timeline from "@/components/Timeline/Timeline"
import Teams from "@/components/Teams/Teams"

const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ""

export default function Home() {
  return (
    <>
      <Head>
        <title>SOI 2024</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={prefix + "/SOI_Favicon.png"} />
      </Head>
      <Layout>
        <Hero />
        <Events />
        <Timeline />
        <Teams />
      </Layout>
    </>
  )
}
