let timeLineData = [
  // {
  //   date: "25th May",
  //   color: "#B983FF",
  //   icon: "Ques",
  // },
  {
    title: "Watch out...for wisdom",
    description: "Old and one-eyed, knowledge hidden within the tree, But I need a little something, another eye for me?",
    date: "25th May",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Seems familiar...I've seen it here before!",
    description: "I'm the secret sauce in Formula 1's race to the top, from aerodynamic wizardry to engine's power, I never stop",
    date: "25th May",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Working for the kings...",
    description: "From victors to victors, pixel to thread, weave the regalia for the crowned head",
    date: "25th May",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Charades...but digital?",
    description: "I'm the bridge between word and sight,\nIn pixels and hues I take flight",
    date: "9th June",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "A romantic tale...or is it?",
    description: "The girl and the boy, going all around, the Anemoi dance at the whims of this pair",
    date: "9th June",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Space...inside?",
    description: "Think outside but also in, Make the space where ideas begin",
    date: "16th June",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Haha funny rat",
    description: "[ADD GIF HERE]",
    date: "23rd June",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Ooooh that's deep",
    description: "From white sand to red rocks, things they dream to see, All alone looking back home, what I see is a Wall blocking mE",
    date: "1st July",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Doesnt sound complete...",
    description: "Across mountains and valleys, the traveler's bull's hooves...",
    date: "4th July",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "... there we go",
    description: "...click clack click clack, Can you guess where he moves?",
    date: "4th July",
    color: "#B983FF",
    icon: "Ques",
  },
  {
    title: "Darkest light...Vantablack?",
    description: "Pitch black my canvas, I carefully tread, Watch the darkest light, for it is the lead",
    date: "7th July",
    color: "#B983FF",
    icon: "Ques",
  },
  // {
  //   title: "Toolset Unbounded",
  //   location: "Coding Club, IIT Dharwad",
  //   description: "Registrations Started.",
  //   date: "27th May - 31st May",
  //   color: "#B983FF",
  //   icon: "CodingClub",
  // },
  // {
  //   title: "AIWars: Conquer the Battlefield",
  //   location: "AI Club, IIT Dharwad",
  //   description: "Event Started",
  //   date: "3rd June",
  //   color: "#00FFFF",
  //   icon: "AIwars",
  // },
  // {
  //   title: "Drone Dash",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "Event Started",
  //   date: "3rd June",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Alokin - Analog",
  //   location: "",
  //   description: "First Checkpoint",
  //   date: "4th June EOD",
  //   color: "#FFB84C",
  //   icon: "Alokin",
  // },
  // {
  //   title: "Toolset Unbounded",
  //   location: "Coding Club, IIT Dharwad",
  //   description: "First Report Submission",
  //   date: "5th June EOD",
  //   color: "#B983FF",
  //   icon: "CodingClub",
  // },
  // {
  //   title: "Alokin - Digital",
  //   location: "",
  //   description: "First Checkpoint",
  //   date: "5th June EOD",
  //   color: "#FFB84C",
  //   icon: "Alokin",
  // },
  // {
  //   title: "Route.AI",
  //   location: "AI Club, IIT Dharwad",
  //   description: "Event Started",
  //   date: "10th June",
  //   color: "#00FFFF",
  //   icon: "AIwars",
  // },
  // {
  //   title: "Rovernomics",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "Registrations Started",
  //   date: "10th June",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Toolset Unbounded",
  //   location: "Coding Club, IIT Dharwad",
  //   description: "Second Report Submission",
  //   date: "12th June EOD",
  //   color: "#B983FF",
  //   icon: "CodingClub",
  // },
  // {
  //   title: "Alokin - Analog",
  //   location: "",
  //   description: "Second Checkpoint",
  //   date: "16th June EOD",
  //   color: "#FFB84C",
  //   icon: "Alokin",
  // },
  // {
  //   title: "AIWars: Conquer the Battlefield",
  //   location: "AI Club, IIT Dharwad",
  //   description: "Submission Deadline",
  //   date: "16th June EOD",
  //   color: "#00FFFF",
  //   icon: "AIwars",
  // },
  // {
  //   title: "Drone Dash",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "Demo Submission",
  //   date: "16th June EOD",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Drone Dash",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "World#1 Release",
  //   date: "17th June",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Route.AI",
  //   location: "AI Club, IIT Dharwad",
  //   description: "Submission Deadline",
  //   date: "17th June EOD",
  //   color: "#00FFFF",
  //   icon: "AIwars",
  // },
  // {
  //   title: "Cosmoscope - Juniors",
  //   location: "Space Data Science club, IIT Dharwad",
  //   description: "Event Started",
  //   date: "17th June",
  //   color: "#F675A8",
  //   icon: "Cosmoscope",
  // },
  // {
  //   title: "Cosmoscope - Seniors",
  //   location: "Space Data Science club, IIT Dharwad",
  //   description: "Event Started",
  //   date: "17th June",
  //   color: "#00FFAB",
  //   icon: "Cosmoscope",
  // },
  // {
  //   title: "Toolset Unbounded",
  //   location: "Coding Club, IIT Dharwad",
  //   description: "Third Report Submission",
  //   date: "24th June EOD",
  //   color: "#B983FF",
  //   icon: "CodingClub",
  // },
  // {
  //   title: "Alokin - Digital",
  //   location: "",
  //   description: "Second Checkpoint",
  //   date: "24th June EOD",
  //   color: "#FFB84C",
  //   icon: "Alokin",
  // },
  // {
  //   title: "Drone Dash",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "World#2 Release",
  //   date: "24th June",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Hack the trade",
  //   location: "Finance Club, IIT Dharwad",
  //   description: "Event Started",
  //   date: "24th June",
  //   color: "#5A96E3",
  //   icon: "Trade",
  // },
  // {
  //   title: "Alokin - Analog",
  //   location: "",
  //   description: "Third Checkpoint",
  //   date: "30th June EOD",
  //   color: "#FFB84C",
  //   icon: "Alokin",
  // },
  // {
  //   title: "Alokin - Digital",
  //   location: "",
  //   description: "Third Checkpoint",
  //   date: "30th June EOD",
  //   color: "#FFB84C",
  //   icon: "Alokin",
  // },
  // {
  //   title: "Toolset Unbounded",
  //   location: "Coding Club, IIT Dharwad",
  //   description: "Final Report Submission",
  //   date: "7th July EOD",
  //   color: "#B983FF",
  //   icon: "CodingClub",
  // },
  // {
  //   title: "Cosmoscope - Juniors",
  //   location: "Space Data Science club, IIT Dharwad",
  //   description: "End Date",
  //   date: "7th July",
  //   color: "#F675A8",
  //   icon: "Cosmoscope",
  // },
  // {
  //   title: "Drone Dash",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "Final Submission",
  //   date: "7th July EOD",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Hack the trade",
  //   location: "Finance Club, IIT Dharwad",
  //   description: "Submission Deadline",
  //   date: "8th July",
  //   color: "#5A96E3",
  //   icon: "Trade",
  // },
  // {
  //   title: "Toolset Unbounded",
  //   location: "Coding Club, IIT Dharwad",
  //   description:
  //     "Project Submission, everything that you have worked past 6 weeks on.",
  //   date: "9th July EOD",
  //   color: "#B983FF",
  //   icon: "CodingClub",
  // },
  // {
  //   title: "Rovernomics",
  //   location: "Robotics Club, IIT Dharwad",
  //   description: "Submission Deadline",
  //   date: "9th July EOD",
  //   color: "white",
  //   icon: "DroneDash",
  // },
  // {
  //   title: "Cosmoscope - Seniors",
  //   location: "Space Data Science club, IIT Dharwad",
  //   description: "End Date",
  //   date: "14th July",
  //   color: "#00FFAB",
  //   icon: "Cosmoscope",
  // },
]

export default timeLineData