let timeLineData = [
  {
    title: "DevShelf",
    location: "Code Geass - Coding Club",
    description: "Watch out... for wisdom; \"Old and one-eyed, bearer of knowledge within the tree, I need a little help now, humans, I call upon thee\" ",
    date: "25th May",
    color: "#000000",
    icon: "Coding",
    secretColor: "#ffffff",
    secretLink: "/Extras/patience.html"
  },
  {
    title: "Innovating Beyond Limits",
    location: "Ingene - Motorsports Club",
    description: "Seems familiar... I've seen it here before; \"I'm the secret sauce in Formula 1's race to the top, from aerodynamic wizardry to engine's power, I never stop\"",
    date: "25th May",
    color: "#ffa000",
    icon: "Motorsports",
  },
  {
    title: "Threads of Triumph",
    location: "Abhikalpa - Design Club",
    description: "Working for the kings; \"From victors to victors, pixel to thread, weave the regalia for the crowned head\"",
    date: "25th May",
    color: "#ff71b7",
    icon: "Design",
  },
  {
    title: "Twins of the Winds",
    location: "Hardly Human - AI Club, Cosmosoc - Space Data Science Club",
    description: "A romantic tale... or is it; \"The girl and the boy, going all around, the Anemoi dance at the whims of this pair\"",
    date: "7th June",
    color: "#f6d32d",
    icon: "SDS",
  },
  {
    title: "StoryForge",
    location: "Hardly Human - AI Club",
    description: "Charades... but digital; \"I'm the bridge between word and sight, In pixels and hues I take flight\"",
    date: "9th June",
    color: "#00FFFF",
    icon: "AI",
  },
  {
    title: "Render in Blender",
    location: "Abhikalpa - Design Club",
    description: "Outer space... inside? ; \"Think outside but also in, Make the space where ideas begin\"",
    date: "16th June",
    color: "#ff71b7",
    icon: "Design",
  },
  {
    title: "MicroMouse",
    location: "Robotics Club",
    gifUrl: "/Timeline/mouse.gif",
    description: "Haha funny rat; But is that a rat or a ...",
    date: "23rd June",
    color: "#ff0000",
    icon: "Robotics",
  },
  {
    title: "Rover Dynamics",
    description: "Ooooh that's deep ; \"From white sand to red rocks, things they dream to see, All alone looking back home, what I see is a Wall blocking mE\"",
    date: "1st July",
    color: "#ffa000",
    icon: "Motorsports",
  },
  //icons: Coding, AI, Robotics, Design, Motorsports, Finance, SDS
  {
    title: "Doesn't sound complete... ",
    description: "Across mountains and valleys, the traveler's bull's hooves... ",
    date: "4th July",
    color: "#0099ff",
    icon: "Ques",
  },
  {
    title: "... there we go",
    description: "... click clack click clack, Can you guess where he moves?",
    date: "4th July",
    color: "#ff0000",
    icon: "Ques",
  },
  {
    title: "Battle scars heal, but new ones come up",
    description: "Are those deep craters, or tall mountains? The mighty Ares paints these with his enemies' blood",
    date: "7th July",
    color: "#00ff00",
    icon: "Ques",
  },
  {
    title: "Darkest light... Vantablack?",
    description: "Pitch black my canvas, I carefully tread, Watch the darkest light, for it is the lead",
    date: "7th July",
    color: "#0099ff",
    icon: "Ques",
  },
]

export default timeLineData
